name: version
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Release Branch'
        required: true
        default: 'v1'
      type:
        description: 'Release Type'
        required: true
        default: 'minor'
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name 'GitHub'
          git config user.email 'noreply@github.com'
          git config -l
      - uses: actions/setup-node@v2
      - run: |
          npm version ${{ github.event.inputs.type }}
          git push --follow-tags
      - run: git fetch --all
      - run: git checkout ${{ github.event.inputs.branch }}
      - run: git log --graph --all --oneline --decorate
      - run: git merge --ff-only master
      - run: git push --follow-tags origin
