name: version
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Release Branch'
        required: true
        default: 'v1'
      type:
        description: 'Release Type'
        required: true
        default: 'minor'
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
      - run: |
          git config user.name 'GitHub'
          git config user.email 'noreply@github.com'
          npm version ${{ github.event.inputs.type }}
          git checkout ${{ github.event.inputs.branch }}
          git merge --ff-only master
          git push --all --follow-tags
